;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mouse-drag-secondary
        mouse-start-secondary
        smarter-move-beginning-of-line
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        ccm-mwheel-scroll
        haml-electric-backspace
        ido-find-file
        ignore
        js-eval-defun
        mouse-set-region
        ns-copy-including-secondary
        ruby-end-space
        undo-tree-visualize
        ))
